### ISSUE TITLE
Is credential.R really only local?

### ISSUE THREAD

**Issue by lucavd** [magnusfurugard/password-protected-shiny#1]
Hi,
I was looking for a simple password-enabled shiny app and your example is the most linear, elegant, and simple I found.

I see in your code that you stated (line #6 of app.R):
`source("./credentials.R") # only exists locally, sets environment variable "secret_password"`

I tried to reproduce your example to shinyapps.io and I succeeded but the file **credentials.R** needs to be uploaded to the server in order to work and it is not encrypted. If I download the bundle the file can be open and read.

Is there I way (that I ignore) to set the password locally and then upload the app? In a way that even if I download the bundle, the password is not shown.

Thank you

**Comment by praktiskt** [comment]
All the file does is to set the `secret_password` environment variable to something only the server knows. I don't really work with R anymore, but I suspect it's possible to set environment variables directly on your shiny app elsewhere.
